### PR TITLE
Stop using long type

### PR DESCRIPTION
**Pull request by uyjulian**
using the long type causes a lot of issue between 32 and 64 bit

### CODE REVIEW

**Comment by sp193** [comment]
Aren't the "common" types like u32 supposed to solve that IOP<-> EE code compatibility?
Not that our SDK is really great for moving code between the two...

**Comment by sp193** [comment]
Why is it necessary to change long int to long long int anyway?
Especially if the code isn't going to be moved over to the other processor?

**Comment by uyjulian** [comment]
@sp193 The "long" type changes to 32-bit integer on 32-bit processor, and 64-bit integer on 64-bit processor.

The "long long" and "int" types don't change.

**Comment by sp193** [comment]
If you put it that way, then on a 16-bit processor, int is 16-bit. If a specific word size is desired, then perhaps it's better to use the defined data types like u32.
The EE has 128-bit registers and has a 64-bit instructions, but our current GCC compiler treats its word size as being 32-bit. long long is supposed to be at least 64-bits in length, so wouldn't assuming that it's always 64-bit not much better than assuming that long is going to be 64-bit?

**Comment by sp193** [comment]
That is, if the code is going to be moved between the IOP and the EE. If the code is staying on either one, I don't see why it's wrong to write the code to be processor-specific.

**Comment by sp193** [comment]
But if anyone else has any other views on this, I'm all ears.
I, as an individual, am just unsure if it's really a great idea because what you're suggesting here will mean that the programming standard of the PS2SDK will change; new code that gets committed should follow this new format, otherwise they will be "wrong".
If I'm not mistaken, your intent is to promote the code interchangeability between the EE and IOP, but I feel that it's best to not specify specific data types (i.e. long long int for 64-bit) if a specific width is required because it still wouldn't guarantee that the right data type will be used.

**Comment by uyjulian** [comment]
I'm closing this since sp193's branch integrated most of my changes.

**Pull request closed without merging**
