### PR TITLE
Implementation of SPEED UART driver

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Review by fjtrujy — APPROVED** [review]

**Comment by israpps** [comment]
This could be used as a nice alternative to UDPTTY on non deckard models right?

**Comment by uyjulian** [comment]
> This could be used as a nice alternative to UDPTTY on non deckard models right?

Yeah, it can be used for that purpose.

**Comment by israpps** [comment]
> > This could be used as a nice alternative to UDPTTY on non deckard models right?
> 
> Yeah, it can be used for that purpose.

any picture showing the pins?

**Comment by uyjulian** [comment]
As far as I know, there aren't any

**Pull request merged**
