### PR TITLE
Add Fatfs as dependency.

### PR DESCRIPTION
**Pull request by Wolf3s**
It needs this: https://github.com/fjtrujy/FatFs/pull/1

### CODE REVIEW

**Review by fjtrujy — APPROVED** [review]
Nice clean!

**Comment by Wolf3s** [comment]
> Nice clean!

Thanks, After this pull request i will focus on smb2man which i hope it will be useful on neutrino.

**Review by uyjulian — APPROVED** [review]
Lgtm

**Comment by Wolf3s** [comment]
Thanks for the merge @fjtrujy, I should focus now on smb2.

**Pull request merged**
