### PR TITLE
Libcglue get drive improvement fix

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by AKuHAK** [comment]
Maybe it will be better to negate this?
Check if path is mass, mc or pfs
use posix
then check cdrom
use windows slash
for other use : only

**Comment by fjtrujy** [comment]
> Maybe it will be better to negate this? Check if path is mass, mc or pfs use posix then check cdrom use windows slash for other use : only

To be honest, I'm not sure, feel free to do whatever you consider the best

**Comment by uyjulian** [comment]
I went ahead and added that change

**Comment by fjtrujy** [comment]
Are you sure this is the solution we want, Imagine the day of tomorrow a new driver added, then most probably we will do supporting the “/“, which means updating that list again.
Then what is happening with HDD partitions? As we can have as many as we want, are these supporting “/“?

**Comment by israpps** [comment]
The list of drives that need special treatment is smaller that the special cases. Deal with edge cases and default to `:/`

Edge cases
- `hdd`
- `rom`
- `cdrom`

Versus
- `mc`
- `pfs`
- `xfrom`
- `mass`
- `dev9x` (?)
- `smb`
- `cdfs`
- etc...

**Comment by uyjulian** [comment]
Yeah I think it would be better to default to posix path handling. I changed it back to to the other behavior

**Pull request merged**
