### PR TITLE
Improve colors in the ELF loader

### PR DESCRIPTION
**Pull request by fjtrujy**
The red color was duplicated, now we have a separate color per step

### CODE REVIEW

**Comment by fjtrujy** [comment]
@israpps you could create a readme in this folder where to put the color documentation

**Comment by israpps** [comment]
> @israpps you could create a readme in this folder where to put the color documentation

Could be possible to make a commit (by someone more experienced than me)

Where all debug colors are documented on comments

Then make a script that reads them all and tabulates on a markdown file maybe?

Just an idea.

**Comment by israpps** [comment]
Oh, now I see that unlike OPL EE core all colors are defined on macro and has small description on comments

What about using those [doxygen groupings](https://www.doxygen.nl/manual/grouping.html) and make the color a group, so descriptions are rendered together

**Comment by fjtrujy** [comment]
I just suggested you in case you were interested.
Having something automatic would be really great.

**Pull request merged**
