### PR TITLE
General Cleanup 7

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by sp193** [comment]
If you remove the F_* definitions, then how can we include only the function that we want?

**Comment by uyjulian** [comment]
I replaced those specifics with ifdefs to `KERNEL_NO_PATCHES` and `_XCDVD`.

**Comment by sp193** [comment]
The original structure of those libraries and their Makefiles was to group the functions and data (typically one function per object) . This would allow only the required functions to be linked, rather than causing all functions within the file to be linked.

Unless, you have a substitute to this?

**Comment by uyjulian** [comment]
Wouldn't only the required functions be linked, and the extra functions be removed on strip?

**Comment by sp193** [comment]
No. You can try it yourself.
Stripping only removes things like symbols and relocations, but the code will remain.

I know that with newer versions of GCC, it can optimize and remove unused code. But the earlier tools we use, do not have such a capability.

**Comment by uyjulian** [comment]
Ah. I'll drop those commits then.

**Pull request merged**
