### PR TITLE
Add Discord badge to readme file

### PR DESCRIPTION
**Pull request by h4570**
Hi.

What do you think guys?
It is good idea to add discord badge in readme?

I think that can be helpful for other guys. For example, I found discord channel very randomly but searched for it, for a long time.

Thanks!

### CODE REVIEW

**Comment by TnA-Plastic** [comment]
Well. It isn't a dev-only server, but there are certainly most people.
It is up to you guys, but it certainly is an honor, that this PR even exists. :)

Best regards,
TnA

**Comment by terremoth** [comment]
I would love to see the badge at Readme.md file. 
That would attract more people interested.

**Comment by h4570** [comment]
Hi guys.

Friendly reminder.

**Comment by rickgaiser** [comment]
The badges show the state of this branch, I don't think we should start using them for links to websites or chat services. Especially if they are not excusively used for ps2dev or ps2dev/ps2sdk. Telling people that 117 people are online discussing ps2dev is misleading information.

I understand that you and other would like to find the link somewhere, but I don't think this is the place to put it.

**Comment by h4570** [comment]
It's sad, because there are many guys, which wants to start ps2dev, but there is no information, where you can get some help. 
In discord there are "ps2sdk", "ps2-homebrew" related channels.

**Comment by terremoth** [comment]
Agreed with h4570.
There could be a way to tell people "there are some people online who can help with ps2 development", of course to tell "117" online is misleading information, but if there could be just a link pointing to the channel, without showing how much people are online, that would be better in my opinion.

**Comment by h4570** [comment]
What do you think guys?

**Comment by TnA-Plastic** [comment]
I think it  might be a good idea, if someone of the developers creates a ps2dev-Discord! 

Possibly dev-only? But that would possibly defy the idea of this PR. 
However... During the last year I noticed, that an open Discord gives newcomers and new developers a better chance to get into the topic.


I think the PS2-Scene-Discord is a good "introduction" and maybe the developers can have an additional Discord (either dev-only/invite-only, OR specifically ON-Topic but open).

**Comment by rickgaiser** [comment]
What I think we need is to get ps2dev.org back.

A website maintained by the developers/enthousiasts. Without adds, or only those needed to keep the site running.
All ps2dev git repositories can link to that site.

ps2dev.org should be the place to get started on ps2 development, with a forum (can we get the old backups back?). With tutorials. And ofcourse, a links section to all the interesting places in the world. Discord can be a great addition, for quick questions and general chat. But the important information should not be in a private Discord, but searchable to everyone on a website/forum.

Anyone know who owns it?
https://www.whois.com/whois/ps2dev.org

Backup ?:
https://ps2linux.no-ip.info/ps2dev/index.php

**Comment by TnA-Plastic** [comment]
Yes, that ultimately would be the most preferable solution!

Naomi (ooPo) is/was the founder and admin of ps2dev.org! I am not quite sure, if she still has a backup somewhere.

I'm going to send her a PM. She recently joined the PS2-Scene-Discord.

Lukasz has a (processed) backup on his site, but I am not quite sure if he is still around or can be traced/contacted.

**Comment by TnA-Plastic** [comment]
She doesn't know if or where she has a backup.

She sent me a link to oobles Twitter (to ask him as well), but sadly I am not on Twitter.
https://twitter.com/oobles

**Comment by ooPo** [comment]
I'm all for having an 'official' chat place, and that discord is probably the best we have at the moment.

There really should be a private dev area on it though. It's often hard to have technical conversations on discord without being interrupted by folks.

Last I heard, the ps2dev.org domain was still owned by Oobles (@oobles on twitter). He may still have it.

I thought I had a dump of the forums from there but I can't seem to find it. I do have dumps of the svn repos but they were what I imported into github here way back when so they're not very useful. :) Someone somewhere probably has a dump.

**Comment by TnA-Plastic** [comment]
Oh, it has 3 or 4 closed channels!

I just haven't yet unlocked everyone to it, because my time is severely limited and I'd rather add everyone into those manually, than the whole Developer-group (although we have so many "on board" now, that I might just do that instead).

**Comment by pedroduarte0** [comment]
> What I think we need is to get ps2dev.org back.

I'm in favor of having a server for knowledge base which the developers have full ownership instead of a generic company like Discord which can decide in their own terms what to do with the information, not to mention that one day it can just go out of business and take down all the conversations. Information is also more difficult (impossible?) to link from outside and harder to  search likely.

I can understand it can be useful to **additionaly** have a chat channel (Discord or any other means) but would be much better in my opinion to host a dedicated server we own for keeping the knowledge.

> Anyone know who owns it?
> https://www.whois.com/whois/ps2dev.org
> 
> Backup ?:
> https://ps2linux.no-ip.info/ps2dev/index.php

[Lukasz](http://lukasz.dk) still keeps his ps2dev.org mirror so it can be accessed at [http://lukasz.dk/mirror/forums.ps2dev.org/index-2.html ](http://lukasz.dk/mirror/forums.ps2dev.org/index-2.html) but most likely it is in read-only state. I believe it should be quite a complete copy if not a full copy before ps2dev.org went down.

He should be reacheable as I believe @terremoth terremoth has contacted him recently... Was it by email?

**Comment by oobles** [comment]
Hi, I'm also oobles on github. I still have the ps2dev.org domain. I'd be happy to direct the dns to a server if someone sets it up and maintains the site. I looked around my archives and have also found the database backup of the phpBB forums from 2010. There's also the original CVS and SVN archives. I've also go the database backup of the website and the Java (JSP) based source code for the server. I have no idea what amount of work it would take to update and get it online, but in theory it is all there.

**Comment by rickgaiser** [comment]
Hello @ooPo and @oobles! It's nice to see two prominent ps2 devs from back in the day!

I'll see if I can find a place to host ps2dev.org. Depending on the costs I can fund it, but I'm very short on time. Are there any volunteers willing to do all the config/restore/update actions needed to get the site back up, and usefull for 2020?

Perhaps this is a good discussion for Discord ;). So we don't flood everyone's email inbox about the how and where.

**Comment by TnA-Plastic** [comment]
I'm gonna write the staff of psxtools.de and STLcardsWS (psx-place.com) a message and ask them, if they could help out.

STLcardsWS has a lot to do, but I hope for Fatman and orc and Chipwelt to be interested in it!


I can "feel the static in the air" (in a positive way)!
PS2dev.org being back online would be so great!


Instead of asking in a closed section (PM, etc.), I might as well create a thread on either of both sites. What do you (all) think?

**Comment by TnA-Plastic** [comment]
The staff at psxtools.de answered here:
https://psxtools.de/forum/index.php?thread/83163-ps2dev-org-wiederbelebung/

So... They are interested in helping out! :)

**Pull request closed without merging**
