### PR TITLE
libmc: replace busyloop checking with semaphore checking

### PR DESCRIPTION
**Pull request by uyjulian**
Busyloop checking is replaced with semaphore checking, so other threads can be run while waiting for RPC.

### CODE REVIEW

**Comment by rickgaiser** [comment]
https://github.com/ps2dev/ps2sdk/blob/1a4587d387022135fbb7eba242c0b10b5b499b8e/ee/kernel/src/sifrpc.c#L179-L201

I like what you're trying to do, but there is no busy waiting loop inside SifCallRpc. Actually, SifCallRpc already uses a semaphore for waiting.

**Comment by uyjulian** [comment]
The busyloop is here: https://github.com/ps2dev/ps2sdk/pull/140/commits/05b422524c62a08e52adb13f921bc92e1c687502#diff-c65198628f56f148984131b4835e6f4cL878

**Comment by sp193** [comment]
As with #141, this change will cause (sce)McSync() to become no longer thread safe and the RPC status becomes inconsistent. If multiple threads call this function, only one will get the signal that the RPC function completed.
The EE kernel does not check on semaphore limits, so I suppose the mechanism might eventually stop working correctly if g_completionSema is allowed to be signalled more than once.

**Comment by uyjulian** [comment]
I copied the design from filexio, so filexio may also have the issue.

**Comment by uyjulian** [comment]
I'll close this, as it would be better to use the filexio functions in some way.

**Comment by sp193** [comment]
The original design is not strictly a less-efficient method; given the design of the EE and IOP kernels, performing this synchronization at the end of your processing or in a thread with a low priority, would result in no loss of useful CPU cycles.

**Pull request closed without merging**
