### PR TITLE
Fixed job server

### PR DESCRIPTION
**Pull request by astrelsky**
I also had to run dos2unix on build-exports.sh but no matter what I did git always ignored the line endings.

Note that `make install` must still be run without jobs. Some of the prerequisite rules clean up without running `make clean` and I couldn't figure out the correct order to run them to make it work with a job server.

### CODE REVIEW

**Comment by fjtrujy** [comment]
Hello thanks to making the PR,
But I don't really understand where and how are you suffering these issues?
On the other hand, I don't understand if the `+` that you're adding could have additional issues.

As you can see we have CI/CD integrated into the repo, and over there we're compiling and generating the samples without any issue.

Could you create a separate branch trying to replicate your issues in the CI/CD? What OS are you using?

Thanks again

**Comment by astrelsky** [comment]
> Hello thanks to making the PR,
> But I don't really understand where and how are you suffering these issues?
> On the other hand, I don't understand if the `+` that you're adding could have additional issues.
> 
> As you can see we have CI/CD integrated into the repo, and over there we're compiling and generating the samples without any issue.
> 
> Could you create a separate branch trying to replicate your issues in the CI/CD? What OS are you using?
> 
> Thanks again

I can make a copy of the output later today. This effectively removes the ‘warning: jobserver unavailable: using -j1. Add `+' to parent make rule.’ warning. You can read more information about it [here](https://www.gnu.org/software/make/manual/html_node/Error-Messages.html) but basically without the `+` they are effectively running with `-j1` instead of the specified number of jobs.

**Comment by AKuHAK** [comment]
Did you check cross-dependencies before? Does each job workflow independent from another? @fjtrujy this PR for making multi-core compilation efficient, some kind of new feature, not error fixing.

**Comment by fjtrujy** [comment]
Ok, so is already working with `-jX`???
@AKuHAK  If this is true, can we modify the CI/CD before merge it to assure that is working using multi-cores?

Thanks

**Comment by astrelsky** [comment]
I have a change coming to fix running `make -jX install` without running building first.

**Comment by astrelsky** [comment]
That should do it. There is a dependency on liberl which is why it was moved to be first. It's not the best way to handle it though.

**Pull request merged**
