### PR TITLE
Errno updates

### PR DESCRIPTION
**Pull request by uyjulian**
Includes descriptions for definitions and also added definitions for 47 and 48

### CODE REVIEW

**Review by fjtrujy — APPROVED** [review]
Nice improvement!

**Comment by israpps** [comment]
since we are dealing with errno. what about adding PS2 error codes there too?

For example. I see on OPL EE Core
```c
#define SCE_EBINDMISS 0x10000 /** Could not bind with RPC server */
#define SCE_ECALLMISS 0x10001 /** Could not call the RPC function */
#define SCE_ELOADMISS 0x10003 /** ELF/Module load failed */
```
are those actual SCE Errors?

**Comment by uyjulian** [comment]
errno.h would be for standard error codes. The `SCE_` prefixed ones aren't there

**Comment by israpps** [comment]
> errno.h would be for standard error codes. The `SCE_` prefixed ones aren't there

oh. didn't saw they're already in loadfile.h

**Pull request merged**
