### PR TITLE
small update to adpenc

### PR DESCRIPTION
**Pull request by KrahJohlito**
This is just to write the fileSize of the input file to the output header... useful to determine duration of the compressed adp later on.

### CODE REVIEW

**Comment by rickgaiser** [comment]
The play duration of an adpcm file is what we're interested in, not the filesize of the original file that was used to generate the adpcm file.

I would prefer this value to be in units of samples. It's the most accurate and usefull unit. Becouse we also record the sample frequency so we can calculate the time in milliseconds if we want to.

A 32bit samples field can hold a maximum of
(2^32) / 48000 / 3600 = 24.8 hours

I think you can use the 'sample_len' field that's already calculated as:
```
		if(fread( &sample_len, 4, 1, fp )==1){
			sample_len /= (channels*2);
		}
```

What do you think?

**Comment by KrahJohlito** [comment]
What calc would we use to determine duration? nSamples / sample rate * channels? I’d like to test before committing but not sure of the formula

**Comment by KrahJohlito** [comment]
adp-test
Left: OPL calculating duration in milliseconds
Right: Actual duration

**Comment by rickgaiser** [comment]
Looks great.

Nice clean 3 line change, squash merging. Thanks.

**Pull request merged**
