### PR TITLE
Set 'noreturn' attribute for longjump()

### PR DESCRIPTION
**Pull request by astrelsky**

### CODE REVIEW

**Comment by sp193** [comment]
Why did you change longjmp() to return an integer?

**Comment by uyjulian** [comment]
longjmp is supposed to return no value, as seen in the standard C specification:
`     void
     longjmp(jmp_buf env, int val);`

**Comment by astrelsky** [comment]
I... I don't know. I realized the contradiction last night and will fix it
this afternoon.

**Comment by astrelsky** [comment]
It appears that I saw the li a0, 1. Mov v0,a0 and then had a brain fart and
went in it's returning and int even though I was initially giving it the no
return attribute.

**Pull request merged**
