### PR TITLE
Provide GitHub accounts for ps2sdk developers before 2012

### PR DESCRIPTION
**Pull request by AKuHAK**
This PR partially fix GitHub commit history (mostly before 2011) as after migrating from SVN only usernames left.
It should work like here: https://github.com/AKuHAK/ps2sdk-history/graphs/contributors?from=2003-12-21&to=2011-09-28&type=c
Also small fix for the main Readme and Authors. Added Discord channel.

### CODE REVIEW

**Comment by AKuHAK** [comment]
@ooPo ooPo
@oobles Oobles
@jbit jbit
@marcusrbrown mrbrown
@asmblur Herben
@enbylnore neovanglist
@jimmikaelkael jim
@tyranid tyranid
@Drakonite drakonite
@nicolasnoble pixel
@gmegidish gawd
@BoGanon ragnarok2040
@lukaszdk lukasz
@x0rloser loser
@t0mb0la t0mb0la
@kdaham blackdroid
@emoon emoon
@mlafeldt mlafeldt
@lavosspawn lavosspawn
@nervus nervus
Hello all! I apologize for the massive ping, but after research made on ps2sdk history seems that you have been working on ps2sdk a long time ago (2003-2011). If I made some mistake, and incorrectly mentioned you, please reply in this thread. Also if for some reason, you do not want to be mentioned, also let me know.
Also, all are welcome on the official [Discord PS2 channel](https://discord.gg/CVFUa9xh6B)!

**Comment by marcusrbrown** [comment]
Hey! Thanks for driving this effort and providing this resource! Yep, `mrbrown` was my username in those days that would have been associated with Subversion.

**Comment by AKuHAK** [comment]
This pr can be merged, other probably will not be found

**Review by marcusrbrown — APPROVED** [review]
There's a typo in the filename linking `AUTHORS2004.md`, but we can fix that on a follow-up 👍🏽.

**Pull request merged**
