### PR TITLE
Fdmap improvements

### PR DESCRIPTION
**Pull request by uyjulian**
This mainly resolves two problems:  
* EE and IOP sockets now can be accessed by same API  
* fileio fds can be used even after switching to fileXio (fixing `stdout` output after switching to fileXio)

### CODE REVIEW

**Comment by fjtrujy** [comment]
Thanks for that amazing contribution!
Is a huge step for a more POSIX environment!
I was thinking of doing a similar approach.
I will try to take a look deeper in the next few days.

Cheers.

**Comment by fjtrujy** [comment]
So far I have a couple of questions:
- Is not this PR going to increase the size of the binaries too much?
- Is working with both path lwip in EE and lwip in IOP?

I suppose you were inspired somehow by the `pspsdk` code, however, we aren't supporting `pipes` as PSP does, is that in your plans? are you going to do this in a separate PR?

**Comment by uyjulian** [comment]
Before this PR:
```
159892	./cube.elf
146388	./pad_example.elf
275988	./teapot.elf
140340	./poweroff_example.elf
155028	./graph.elf
165652	./ps2tests.elf
359316	./texture.elf
147668	./playwav.elf
141812	./testcd.elf
270932	./tcpip_dhcp_example.elf
270708	./tcpip_basic_example.elf
136404	./test_systemTime.elf
141396	./helloworld.elf
138964	./ps2snd-sample.elf
214716	./vu1.elf
136724	./test_alarm_stop.elf
146740	./playwav2.elf
147636	./playadpcm.elf
142100	./nanosleep_test.elf
163796	./remote_sample.elf
147380	./padx_sample.elf
137364	./callstacktest.elf
137748	./mem_test.elf
136532	./test_alarm_sleep.elf
144436	./rewinddir_test.elf
247252	./font.elf
141140	./ee-echo.elf
152500	./filexio_sample.elf
149940	./timezone_test.elf
56148	./nanoHelloWorld.elf
136692	./test_alarm.elf
145780	./main.elf
128372	./test_noPatchedHelloWorld.elf
143380	./playcdda.elf
145140	./mtap_sample.elf
5752004	total
```
After this PR:
```
162932	./cube.elf
149428	./pad_example.elf
279028	./teapot.elf
143252	./poweroff_example.elf
158196	./graph.elf
168180	./ps2tests.elf
362484	./texture.elf
150836	./playwav.elf
144980	./testcd.elf
305396	./tcpip_dhcp_example.elf
305332	./tcpip_basic_example.elf
139572	./test_systemTime.elf
144564	./helloworld.elf
142132	./ps2snd-sample.elf
217756	./vu1.elf
139764	./test_alarm_stop.elf
149908	./playwav2.elf
150676	./playadpcm.elf
145140	./nanosleep_test.elf
166836	./remote_sample.elf
150548	./padx_sample.elf
140532	./callstacktest.elf
141236	./mem_test.elf
139444	./test_alarm_sleep.elf
147604	./rewinddir_test.elf
250420	./font.elf
151764	./ee-echo.elf
155060	./filexio_sample.elf
153108	./timezone_test.elf
59188	./nanoHelloWorld.elf
139604	./test_alarm.elf
148692	./main.elf
131540	./test_noPatchedHelloWorld.elf
146420	./playcdda.elf
148308	./mtap_sample.elf
5929860	total
```

It appears there is a 3% increase of executable size so it won't increase the size of the binaries too much.  

This works with either of lwip in EE or lwip in IOP (at the moment, not both at the same time)

Probably won't do `pipes` at this time, especially since EE kernel doesn't have any supporting functionality for it.

**Comment by Wolf3s** [comment]
> This mainly resolves two problems:
> 
> * EE and IOP sockets now can be accessed by same API
> * fileio fds can be used even after switching to fileXio (fixing `stdout` output after switching to fileXio)

Hey, i´ve done some tests related to the pull-request, i found that newlib api on iop part, net headers appears to be missing, even it´s separated.
Screenshot_3

**Comment by Wolf3s** [comment]
but in rest sounds ok for now.

**Comment by uyjulian** [comment]
These set of changes intentionally don't modify IOP related stuff, because the fdmap/libcglue code is on EE.  
What worked previously on IOP, however, should continue to work.

**Comment by Wolf3s** [comment]
> These set of changes intentionally don't modify IOP related stuff, because the fdmap/libcglue code is on EE. What worked previously on IOP, however, should continue to work.

Curious, however EE sounds work pretty well.

**Comment by Wolf3s** [comment]
Yet, it needs to document more functions.

**Comment by Wolf3s** [comment]
https://github.com/uyjulian/ps2sdk/blob/fdmap_improvements/common/include/ps2ip_rpc.h this place regards newlib function

**Comment by uyjulian** [comment]
Adding additional documentation is not a part of this PR, since it is intended to use the standard socket function which is documented plentiful.

**Comment by Wolf3s** [comment]
> That file is not modified in this PR.
> 
> Adding additional documentation is not a part of this PR, since it is intended to use the standard socket function which is documented plentiful.

Better leave that file for other moment then.

**Comment by fjtrujy** [comment]
Do you plan to add at least 2 examples? One for EE path and another one for the IOP path?
Also now following the code is a little more complex, would be nice if we update the `libcglue` readme by adding if it is possible a schema or diagram flow

**Comment by uyjulian** [comment]
The current `tcpip_basic`, `tcpip_dhcp` (for EE), and `tcpips` (for IOP) samples continue to work.  

Also added a diagram.

**Comment by fjtrujy** [comment]
> The current `tcpip_basic`, `tcpip_dhcp` (for EE), and `tcpips` (for IOP) samples continue to work.
> 
> Also added a diagram.

There is still a sample that I miss (I know it wasn't before), but I don't see a sample that uses whole lwip functionality in IOP.
`tcpips` sample, is a sample that uses the `EE rpc` library `libtcpips.a` which changes messages with `ps2ips.irx`, however `ps2ips.irx` on the imports has dependencies to `lwip_` which actually belong to `ps2ip-nm.irx` (I suppose that name is PS2IP because it actually uses lwip and `nm` because it uses `netman`), so I still miss a sample that uses the whole flow having the stack on IOP.

Is fine if you don't want to create the sample now in your PR, feel free to ignore this message.

**Comment by uyjulian** [comment]
I'll probably do IOP side samples in a separate PR

**Review by fjtrujy — APPROVED** [review]

**Pull request merged**
