### PR TITLE
Use original error return values for IO stub ops

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by Wolf3s** [comment]
I will test this.

**Comment by Wolf3s** [comment]
Looks fine in the same state.

**Comment by fjtrujy** [comment]
@uyjulian any reason why we want to do this? any particular error being reported?

**Comment by uyjulian** [comment]
> @uyjulian any reason why we want to do this? any particular error being reported?

imgdrv was broken because it was returning the wrong result for open

**Pull request merged**
