### PR TITLE
General cleanup 9

### PR DESCRIPTION
**Pull request by uyjulian**
Various cleanup, using the issues pointed out by Codacy as a guide.

### CODE REVIEW

**Comment by terremoth** [comment]
Awwwwsome

**Comment by uyjulian** [comment]
It seems like I broke something (OPL won't boot), so I'll probably revisit this later and figure out what broke.

**Comment by uyjulian** [comment]
For now, I dropped the signedness and if…do…while related changes.  
OPL now works.

**Comment by AKuHAK** [comment]
@uyjulian when do you plan to merge it? I also want to clean the code, but it is better to make it over your submission.

**Comment by uyjulian** [comment]
It is OK to merge
--
~Julian Uy

**Review by fjtrujy — APPROVED** [review]

**Pull request merged**
