### PR TITLE
Update `FatFS` dependency to version `0.15` and apply `IOP` changes

### PR DESCRIPTION
**Pull request by fjtrujy**
## Description

This PR updates the `FatFS` code to the latest version `0.15` November 2022 and also it applies the specific needed IOP changes.

Things to take into consideration:
- The specific IOP changes are easier to see in this repo: https://github.com/fjtrujy/FatFs/commit/abe697bce726c8fa9bea7d34a3b91848545aa369
- If you see typos or code style changes, it belongs to the original author's code 

Specific changelog coming from original FatFS repo:
- Changed user provided synchronization functions in order to completely eliminate the platform dependency from FatFs code.
- FF_SYNC_t is removed from the configuration options.
- Fixed a potential error in f_mount when FF_FS_REENTRANT.
- Fixed file lock control FF_FS_LOCK is not mutal excluded when FF_FS_REENTRANT && FF_VOLUMES > 1 is true.
- Fixed f_mkfs() creates broken exFAT volume when the size of volume is >= 2^32 sectors.
- Fixed string functions cannot write the unicode characters not in BMP when FF_LFN_UNICODE == 2 (UTF-8).
- Fixed a compatibility issue in identification of GPT header.

Cheers

### CODE REVIEW

**Comment by Wolf3s** [comment]
Did you test this with opl?

**Comment by fjtrujy** [comment]
> Did you test this with opl?

Not yet, I did it with some other programs and it worked fine.
@AKuHAK could you test it using OPL?

**Comment by Wolf3s** [comment]
> > Did you test this with opl?
> 
> Not yet, I did it with some other programs and it worked fine. @AKuHAK could you test it using OPL?

I will test by myself then.

**Review by uyjulian — APPROVED** [review]
Code changes lgtm, wLE can launch itself, OPL USB loading works

**Comment by fjtrujy** [comment]
> Code changes lgtm, wLE can launch itself, OPL USB loading works

Cool! Enough to merge it!
Thanks

**Pull request merged**
