### PR TITLE
Merge portability and other related changes from pfsshell

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Review by AKuHAK — APPROVED** [review]
isnt this dangerous? I mean that some app can try to write past the HDD end

**Comment by AKuHAK** [comment]
> isnt this dangerous? I mean that some app can try to write past the HDD end

its about https://github.com/ps2dev/ps2sdk/pull/311/commits/eba6acbc65b68f4cd891a94e78d159577a84fd12

**Comment by uyjulian** [comment]
> > isnt this dangerous? I mean that some app can try to write past the HDD end
> 
> its about [eba6acb](https://github.com/ps2dev/ps2sdk/commit/eba6acbc65b68f4cd891a94e78d159577a84fd12)

This is optional and not enabled by default

**Comment by rickgaiser** [comment]
@uyjulian can you fix the conflict? Then I'll merge it.

**Comment by uyjulian** [comment]
Fixed merge conflicts

**Pull request merged**
