### PR TITLE
fix for sandisk sdcards

### PR DESCRIPTION
**Pull request by qnox32**
```
if (spi_ss == 0) {
        // We're ignoring a lot of dummy read/writes, this is not an error
        // M_DEBUG("%s(%d) - ignoring, not selected\n", __FUNCTION__, byte);
        return 0;
}
```
This check renders every instance of the following useless:
```
in spi_sdcard_driver.c:
_io->wr_rd_byte(DUMMY_BYTE);
_io->select();

_io->relese();
_io->wr_rd_byte(DUMMY_BYTE);
```  
As a result the clock is not toggled when it should be and this leads to issues with SanDisk sdcards. I'm not sure if this check was a means of optimization or an oversight. I haven't done any performance testing beyond loading up Half-Life with OPL, which seems okay. 

I've tested this fix with a 128GB SanDisk SDXC and a 16GB no brand SDHC, both seem to be fully working. Previously the 16GB would only be detected and wasnt able to get far enough to load a list of games and the SanDisk wouldn't respond at all.

EDIT:
test_bdm results on a SCPH-750001.

128GB SanDisk SDXC:
```
Read 1024KiB, in 5149ms, blocksize=64, speed=203KB/s
Read 1024KiB, in 2970ms, blocksize=128, speed=353KB/s
Read 1024KiB, in 1845ms, blocksize=256, speed=568KB/s
Read 1024KiB, in 1414ms, blocksize=512, speed=741KB/s
Read 1024KiB, in 1184ms, blocksize=1024, speed=885KB/s
Read 1024KiB, in 1085ms, blocksize=2048, speed=966KB/s
Read 1024KiB, in 1059ms, blocksize=4096, speed=990KB/s
Read 1024KiB, in 1049ms, blocksize=8192, speed=999KB/s
Read 1024KiB, in 1040ms, blocksize=16384, speed=1008KB/s
Read 1024KiB, in 1039ms, blocksize=32768, speed=1009KB/s
```  

16GB no brand SDHC:
```
Read 1024KiB, in 5104ms, blocksize=64, speed=205KB/s
Read 1024KiB, in 2947ms, blocksize=128, speed=355KB/s
Read 1024KiB, in 1837ms, blocksize=256, speed=570KB/s
Read 1024KiB, in 1408ms, blocksize=512, speed=744KB/s
Read 1024KiB, in 1164ms, blocksize=1024, speed=900KB/s
Read 1024KiB, in 1023ms, blocksize=2048, speed=1025KB/s
Read 1024KiB, in 983ms, blocksize=4096, speed=1066KB/s
Read 1024KiB, in 955ms, blocksize=8192, speed=1097KB/s
Read 1024KiB, in 940ms, blocksize=16384, speed=1115KB/s
Read 1024KiB, in 941ms, blocksize=32768, speed=1114KB/s
``` 

Unfortunately, I have no way of testing if this change will result in performance regression on already supported cards.

### CODE REVIEW

**Comment by qnox32** [comment]
A user in the PS2-Scene Discord server has tested the changes in my last commit [edf475f](https://github.com/ps2dev/ps2sdk/pull/402/commits/edf475f45af9b80377a62a4797936d20efca6646) and found they restored compatibility with their cards, however, this is only one such case. I am unable to test anything beyond a handful of SanDisk cards. I will be providing below a build of OPL for testing and a build of test_bdm for debugging problematic cards.

Note: ps2link and ps2client are required for test_bdm.

OPL: https://www.dropbox.com/s/lpvge0ca13jevhr/OPNPS2LD_R4.ELF?dl=0
test_bdm: https://www.dropbox.com/s/a0c2aqpdxfm2m8x/test_bdm_R4.elf?dl=0

**Comment by israpps** [comment]
> A user in the PS2-Scene Discord server has tested the changes in my last commit [edf475f](https://github.com/ps2dev/ps2sdk/pull/402/commits/edf475f45af9b80377a62a4797936d20efca6646) and found they restored compatibility with their cards, however, this is only one such case. I am unable to test anything beyond a handful of SanDisk cards. I will be providing below a build of OPL for testing and a build of test_bdm for debugging problematic cards.
> 
> Note: ps2link and ps2client are required for test_bdm.
> 
> OPL: https://www.dropbox.com/s/lpvge0ca13jevhr/OPNPS2LD_R4.ELF?dl=0 test_bdm: https://www.dropbox.com/s/a0c2aqpdxfm2m8x/test_bdm_R4.elf?dl=0

I can test on a thoshiba exceria. wich is supposed to be the most compatible card with the mx4sio driver

**Comment by INDRAPhilip** [comment]
> Um usuário no servidor PS2-Scene Discord testou as alterações no meu último commit [edf475f](https://github.com/ps2dev/ps2sdk/pull/402/commits/edf475f45af9b80377a62a4797936d20efca6646) e descobriu que eles restauraram a compatibilidade com suas placas, no entanto, este é apenas um desses casos. Eu sou incapaz de testar qualquer coisa além de um punhado de cartões SanDisk. Fornecerei abaixo uma compilação do OPL para testes e uma compilação do test_bdm para depuração de cartões problemáticos.
> 
> Nota: ps2link e ps2client são necessários para test_bdm.
> 
> OPL: https://www.dropbox.com/s/lpvge0ca13jevhr/OPNPS2LD_R4.ELF?dl=0 test_bdm: https://www.dropbox.com/s/a0c2aqpdxfm2m8x/test_bdm_R4.elf?dl=0

It seems to work fine with Netac 128 GB SD, Sandisk 16 GB and a generic 16 GB in my gaming and app tests, but I could compile it with the BDM4 drive it performs better for MX4SIO over the standard opl version.

**Comment by qnox32** [comment]
More results from commit #[edf475f](https://github.com/ps2dev/ps2sdk/pull/402/commits/edf475f45af9b80377a62a4797936d20efca6646):

These come from a user in the MX4SIO thread:

"Kingston 128GB microSD EXFAT - works (change!)
SanDisk 200gb microSD EXFAT - works (no change)
Sony 16GB SD FAT32 - doesn't work (no change)
SanDisk 16GB SD FAT32 - works (no change)
Samsung 4GB SD FAT32 - works (change!)"

Here is a new binary for debugging compatibility issues. It's similar to test_bdm except everything is logged to a USB flash drive and it does not require ps2link/ps2client. To use it all you need to do is connect a FAT32 formatted flash drive and load the ELF with uLaunchELF. Once it's complete it will automatically exit and there should be a new file on the flash drive called "sdcard_log.txt" 

sdcard_debugger: https://www.dropbox.com/s/fnffuptnqf78orx/sdcard_debugger.elf?dl=0

If you are having compatibility issues, please run this and submit the logs.

**Pull request merged**
